#ifndef RESOURCE_MANAGER_GENERAL_INCLUDES_H_
#define RESOURCE_MANAGER_GENERAL_INCLUDES_H_

// default width and height
#define WIDTH	800
#define HEIGHT	600

#endif // RESOURCE_MANAGER_GENERAL_INCLUDES_H_